import type { GenerateApiSpecInput } from "../tools/schemas.js";
import { renderReport, type RiskEntry, type Verdict } from "./template.js";

const SCHEMA_VERSION = "1.0.0";

const TIER_LIMITS: Record<string, { perMinute: number; burst: number }> = {
  standard: { perMinute: 60, burst: 10 },
  elevated: { perMinute: 600, burst: 50 },
  unlimited: { perMinute: 0, burst: 0 },
};

/**
 * Renders a full enterprise OpenAPI 3.1.0 spec wrapped in a templated report.
 * Returns the rendered markdown report. The OpenAPI YAML is embedded in the
 * Findings section AND in the JSON envelope payload for downstream consumers.
 */
export function generateEnterpriseApiSpec(input: GenerateApiSpecInput): string {
  const yaml = buildOpenApiYaml(input);
  const risks = collectRisks(input);
  const verdict = pickVerdict(risks);
  const major = input.version.split(".")[0];

  const tierUsage = countByTier(input);
  const idempotentCount = input.endpoints.filter((e) => e.requires_idempotency).length;
  const deprecatedCount = input.endpoints.filter((e) => e.deprecated).length;

  return renderReport({
    tool: "generate_enterprise_api_spec",
    schemaVersion: SCHEMA_VERSION,
    title: `Enterprise API Specification: ${input.title}`,
    context: {
      api_title: input.title,
      api_version: input.version,
      base_path: `/v${major}`,
      endpoint_count: input.endpoints.length,
      idempotent_endpoints: idempotentCount,
      deprecated_endpoints: deprecatedCount,
      rate_limit_tiers_in_use: Object.entries(tierUsage)
        .map(([tier, n]) => `${tier}=${n}`)
        .join(", "),
    },
    executiveSummary: buildExecutiveSummary(input, verdict, risks.length),
    verdict,
    findings: [
      {
        heading: "3.1 Generated OpenAPI 3.1.0 Specification",
        body: ["```yaml", yaml, "```"].join("\n"),
      },
      {
        heading: "3.2 Endpoint Inventory",
        body: buildEndpointTable(input),
      },
      {
        heading: "3.3 Enforced Conventions",
        body: buildConventionsBlock(input),
      },
      {
        heading: "3.4 Quality Gate Checklist",
        body: buildQualityGateChecklist(input),
      },
    ],
    risks,
    recommendations: buildRecommendations(input, risks),
    nextSteps: [
      { step: "Review the generated YAML against domain stakeholders" },
      { step: "Run the spec through `spectral lint` and `openapi-validator`" },
      { step: "Generate client SDKs from the spec (typescript-axios, openapi-generator)" },
      { step: "Wire the spec into CI: fail builds if endpoints diverge from this contract" },
      { step: "Publish the spec to the developer portal at /docs" },
    ],
    reEvaluateIn: "before each minor version release",
    payload: {
      openapi_yaml: yaml,
      endpoint_count: input.endpoints.length,
      api_version: input.version,
      base_path: `/v${major}`,
      tier_usage: tierUsage,
      idempotent_endpoints: idempotentCount,
      deprecated_endpoints: deprecatedCount,
    },
  });
}

// ---------------------------------------------------------------------------
// OpenAPI YAML construction
// ---------------------------------------------------------------------------

function buildOpenApiYaml(input: GenerateApiSpecInput): string {
  const major = input.version.split(".")[0];
  const lines: string[] = [
    "openapi: 3.1.0",
    "info:",
    `  title: ${quote(input.title)}`,
    `  version: ${quote(input.version)}`,
    `  description: ${quote(`Enterprise API for ${input.title}. Generated by sdlc-feature-planning-server. Enforces auth, idempotency, RFC 7807 errors, rate limits, pagination, deprecation lifecycle, and CORS allowlist.`)}`,
    "servers:",
    `  - url: https://api.yourdomain.com/v${major}`,
    "    description: Production",
    `  - url: https://staging-api.yourdomain.com/v${major}`,
    "    description: Staging",
    "security:",
    "  - BearerJWT: []",
    "tags:",
    ...uniqueTags(input).map((t) => `  - name: ${t}`),
    "paths:",
  ];

  for (const ep of input.endpoints) {
    lines.push(...renderPath(ep));
  }

  lines.push(...renderComponents());
  return lines.join("\n");
}

function renderPath(ep: GenerateApiSpecInput["endpoints"][number]): string[] {
  const method = ep.method.toLowerCase();
  const tag = deriveTag(ep.path);
  const lines: string[] = [
    `  ${ep.path}:`,
    `    ${method}:`,
    `      tags: [${tag}]`,
    `      summary: ${quote(ep.summary)}`,
    `      operationId: ${operationId(ep.method, ep.path)}`,
  ];

  if (ep.deprecated) {
    lines.push("      deprecated: true");
  }

  // Auth
  const security =
    ep.auth_scheme === "none"
      ? "      security: []"
      : `      security:\n        - ${authSchemeRef(ep.auth_scheme ?? "bearer_jwt")}: []`;
  lines.push(security);

  // Parameters: path params + global request id + idempotency
  const pathParams = extractPathParams(ep.path);
  const params: string[] = [];
  params.push("        - $ref: '#/components/parameters/XRequestId'");
  for (const p of pathParams) {
    params.push(`        - name: ${p}`);
    params.push("          in: path");
    params.push("          required: true");
    params.push("          schema: { type: string }");
  }
  if (ep.requires_idempotency || ep.method === "POST" || ep.method === "PUT") {
    params.push("        - $ref: '#/components/parameters/IdempotencyKey'");
  }
  if (ep.pagination_strategy === "cursor") {
    params.push("        - $ref: '#/components/parameters/Cursor'");
    params.push("        - $ref: '#/components/parameters/PageSize'");
  } else if (ep.pagination_strategy === "offset") {
    params.push("        - $ref: '#/components/parameters/Page'");
    params.push("        - $ref: '#/components/parameters/PageSize'");
  }
  lines.push("      parameters:", ...params);

  // Request body for write methods
  if (ep.method === "POST" || ep.method === "PUT" || ep.method === "PATCH") {
    lines.push(
      "      requestBody:",
      "        required: true",
      "        content:",
      "          application/json:",
      "            schema:",
      "              type: object",
      "              additionalProperties: true",
    );
  }

  // Responses
  const successStatus = ep.method === "POST" ? "201" : ep.method === "DELETE" ? "204" : "200";
  lines.push("      responses:");
  lines.push(`        '${successStatus}':`);
  lines.push(`          description: Success`);
  lines.push("          headers:");
  lines.push("            X-Request-ID: { $ref: '#/components/headers/XRequestId' }");
  lines.push("            X-RateLimit-Limit: { $ref: '#/components/headers/XRateLimitLimit' }");
  lines.push(
    "            X-RateLimit-Remaining: { $ref: '#/components/headers/XRateLimitRemaining' }",
  );
  lines.push("            X-RateLimit-Reset: { $ref: '#/components/headers/XRateLimitReset' }");
  if (ep.deprecated) {
    lines.push("            Deprecation: { $ref: '#/components/headers/Deprecation' }");
    lines.push("            Sunset: { $ref: '#/components/headers/Sunset' }");
  }
  if (successStatus !== "204") {
    if (ep.pagination_strategy !== "none" && ep.method === "GET") {
      lines.push(
        "          content:",
        "            application/json:",
        "              schema:",
        ep.pagination_strategy === "cursor"
          ? "                $ref: '#/components/schemas/CursorPage'"
          : "                $ref: '#/components/schemas/OffsetPage'",
      );
    } else {
      lines.push(
        "          content:",
        "            application/json:",
        "              schema: { type: object, additionalProperties: true }",
      );
    }
  }

  // Standard error responses
  for (const status of ["400", "401", "403", "404", "422", "429", "503"]) {
    lines.push(`        '${status}':`);
    lines.push(`          $ref: '#/components/responses/${responseRef(status)}'`);
  }

  return lines;
}

function renderComponents(): string[] {
  return [
    "components:",
    "  securitySchemes:",
    "    BearerJWT:",
    "      type: http",
    "      scheme: bearer",
    "      bearerFormat: JWT",
    "      description: JWT signed with RS256/ES256. Validates iss, aud, exp, nbf. alg=none rejected.",
    "    OAuth2ClientCredentials:",
    "      type: oauth2",
    "      flows:",
    "        clientCredentials:",
    "          tokenUrl: https://auth.yourdomain.com/oauth2/token",
    "          scopes: {}",
    "    ApiKey:",
    "      type: apiKey",
    "      in: header",
    "      name: X-API-Key",
    "  parameters:",
    "    XRequestId:",
    "      name: X-Request-ID",
    "      in: header",
    "      required: false",
    "      schema: { type: string, format: uuid }",
    "      description: Correlation ID. Server generates one if absent.",
    "    IdempotencyKey:",
    "      name: Idempotency-Key",
    "      in: header",
    "      required: true",
    "      schema: { type: string, format: uuid }",
    "      description: UUID v4. Server stores key+response for 24h. Reuse with different body returns 422 IDEMPOTENCY_KEY_REUSE.",
    "    Cursor:",
    "      name: cursor",
    "      in: query",
    "      schema: { type: string }",
    "    Page:",
    "      name: page",
    "      in: query",
    "      schema: { type: integer, minimum: 1, default: 1 }",
    "    PageSize:",
    "      name: page_size",
    "      in: query",
    "      schema: { type: integer, minimum: 1, maximum: 100, default: 25 }",
    "  headers:",
    "    XRequestId:",
    "      schema: { type: string, format: uuid }",
    "    XRateLimitLimit:",
    "      schema: { type: integer }",
    "    XRateLimitRemaining:",
    "      schema: { type: integer }",
    "    XRateLimitReset:",
    "      schema: { type: integer, format: int64 }",
    "    Deprecation:",
    "      schema: { type: string }",
    "      description: 'true' or RFC 3339 deprecation date.",
    "    Sunset:",
    "      schema: { type: string, format: date-time }",
    "    RetryAfter:",
    "      schema: { type: integer }",
    "  schemas:",
    "    ProblemDetail:",
    "      type: object",
    "      required: [type, title, status, detail, error_code, request_id, timestamp]",
    "      properties:",
    "        type: { type: string, format: uri }",
    "        title: { type: string }",
    "        status: { type: integer }",
    "        detail: { type: string }",
    "        instance: { type: string }",
    "        error_code: { type: string, pattern: '^[A-Z][A-Z0-9_]+$' }",
    "        request_id: { type: string, format: uuid }",
    "        timestamp: { type: string, format: date-time }",
    "    CursorPage:",
    "      type: object",
    "      required: [data, pagination]",
    "      properties:",
    "        data: { type: array, items: { type: object, additionalProperties: true } }",
    "        pagination:",
    "          type: object",
    "          required: [has_next_page, has_previous_page]",
    "          properties:",
    "            has_next_page: { type: boolean }",
    "            has_previous_page: { type: boolean }",
    "            next_cursor: { type: string, nullable: true }",
    "            previous_cursor: { type: string, nullable: true }",
    "    OffsetPage:",
    "      type: object",
    "      required: [data, pagination]",
    "      properties:",
    "        data: { type: array, items: { type: object, additionalProperties: true } }",
    "        pagination:",
    "          type: object",
    "          required: [total, page, page_size, total_pages]",
    "          properties:",
    "            total: { type: integer }",
    "            page: { type: integer }",
    "            page_size: { type: integer }",
    "            total_pages: { type: integer }",
    "  responses:",
    ...errorResponse("BadRequest", "400", "BAD_REQUEST"),
    ...errorResponse("Unauthenticated", "401", "UNAUTHENTICATED"),
    ...errorResponse("Unauthorized", "403", "UNAUTHORIZED"),
    ...errorResponse("NotFound", "404", "RESOURCE_NOT_FOUND"),
    ...errorResponse("ValidationFailed", "422", "VALIDATION_FAILED"),
    ...errorResponseWithRetry("RateLimited", "429", "RATE_LIMIT_EXCEEDED"),
    ...errorResponseWithRetry("ServiceUnavailable", "503", "SERVICE_UNAVAILABLE"),
  ];
}

function errorResponse(name: string, status: string, code: string): string[] {
  return [
    `    ${name}:`,
    `      description: ${status} ${code}`,
    "      content:",
    "        application/problem+json:",
    "          schema: { $ref: '#/components/schemas/ProblemDetail' }",
  ];
}

function errorResponseWithRetry(name: string, status: string, code: string): string[] {
  return [
    `    ${name}:`,
    `      description: ${status} ${code}`,
    "      headers:",
    "        Retry-After: { $ref: '#/components/headers/RetryAfter' }",
    "      content:",
    "        application/problem+json:",
    "          schema: { $ref: '#/components/schemas/ProblemDetail' }",
  ];
}

// ---------------------------------------------------------------------------
// Risk + verdict
// ---------------------------------------------------------------------------

function collectRisks(input: GenerateApiSpecInput): RiskEntry[] {
  const risks: RiskEntry[] = [];

  for (const ep of input.endpoints) {
    if (ep.auth_scheme === "none") {
      risks.push({
        id: `AUTH-${operationId(ep.method, ep.path)}`,
        severity: "high",
        description: `Endpoint ${ep.method} ${ep.path} is unauthenticated.`,
        mitigation:
          "Confirm this endpoint is intentionally public; apply IP-based rate limiting and bot detection.",
      });
    }
    if ((ep.method === "POST" || ep.method === "PUT") && !ep.requires_idempotency) {
      risks.push({
        id: `IDEMP-${operationId(ep.method, ep.path)}`,
        severity: "medium",
        description: `${ep.method} ${ep.path} lacks explicit idempotency enforcement.`,
        mitigation: "Set requires_idempotency=true so clients must send Idempotency-Key.",
      });
    }
    if (ep.rate_limit_tier === "unlimited") {
      risks.push({
        id: `RATE-${operationId(ep.method, ep.path)}`,
        severity: "medium",
        description: `Endpoint ${ep.method} ${ep.path} has unlimited rate tier.`,
        mitigation:
          "Restrict 'unlimited' tier to internal service accounts only; verify caller identity.",
      });
    }
    if (ep.deprecated && ep.sunset_date) {
      const sunsetMs = Date.parse(ep.sunset_date);
      const sixMonthsMs = 1000 * 60 * 60 * 24 * 30 * 6;
      if (sunsetMs - Date.now() < sixMonthsMs) {
        risks.push({
          id: `SUNSET-${operationId(ep.method, ep.path)}`,
          severity: "high",
          description: `Sunset date ${ep.sunset_date} is less than 6 months away.`,
          mitigation:
            "Extend sunset to ≥ 6 months from today, or document the breaking-change exception.",
        });
      }
    }
  }

  // Major version 0 is a stability signal
  if (input.version.startsWith("0.")) {
    risks.push({
      id: "VERSION-PRE-1.0",
      severity: "low",
      description: "API version is pre-1.0; consumers should expect breaking changes.",
      mitigation: "Mark the API as 'beta' in documentation and avoid SLA commitments.",
    });
  }

  return risks;
}

function pickVerdict(risks: RiskEntry[]): Verdict {
  if (risks.some((r) => r.severity === "blocker")) return "reject";
  if (risks.some((r) => r.severity === "high")) return "approve_with_conditions";
  if (risks.some((r) => r.severity === "medium")) return "approve_with_conditions";
  return "approve";
}

function buildExecutiveSummary(
  input: GenerateApiSpecInput,
  verdict: Verdict,
  riskCount: number,
): string {
  const verdictText = {
    approve: "ready for implementation",
    approve_with_conditions:
      "ready for implementation once the documented conditions are addressed",
    reject: "blocked from implementation pending fixes to the listed risks",
    needs_review: "requires further review before proceeding",
  }[verdict];
  return [
    `This OpenAPI 3.1.0 specification for **${input.title}** v${input.version} is **${verdictText}**.`,
    `It defines ${input.endpoints.length} endpoint(s) and enforces JWT auth, RFC 7807 errors, idempotency on writes, cursor/offset pagination, and the standard rate-limit header set.`,
    riskCount === 0
      ? "No risks were detected during contract synthesis."
      : `${riskCount} risk(s) were detected — see the Risk Register for severity and required mitigations.`,
  ].join(" ");
}

// ---------------------------------------------------------------------------
// Body sections
// ---------------------------------------------------------------------------

function buildEndpointTable(input: GenerateApiSpecInput): string {
  const rows = input.endpoints.map(
    (e) =>
      `| \`${e.method}\` | \`${e.path}\` | ${escape(e.summary)} | ${e.auth_scheme ?? "bearer_jwt"} | ${e.rate_limit_tier ?? "standard"} | ${e.pagination_strategy} | ${e.requires_idempotency ? "✅" : "—"} | ${e.deprecated ? `⚠️ sunset ${e.sunset_date}` : "—"} |`,
  );
  return [
    "| Method | Path | Summary | Auth | Rate Limit | Pagination | Idempotent | Deprecation |",
    "|---|---|---|---|---|---|---|---|",
    ...rows,
  ].join("\n");
}

function buildConventionsBlock(input: GenerateApiSpecInput): string {
  const stdLimit = TIER_LIMITS.standard;
  const elevLimit = TIER_LIMITS.elevated;
  return [
    "**Authentication.** Default `BearerJWT` (RS256/ES256). `alg: none` rejected. JWT claims `iss`, `aud`, `exp`, `nbf` validated.",
    "",
    "**Idempotency.** All `POST`/`PUT` (and any endpoint with `requires_idempotency=true`) must include `Idempotency-Key: <uuid v4>`. Server stores key→response for 24 h; reuse with a different body yields `422 IDEMPOTENCY_KEY_REUSE`.",
    "",
    "**Errors.** RFC 7807 `application/problem+json` with mandatory `error_code` (UPPER_SNAKE_CASE), `request_id`, `timestamp`.",
    "",
    `**Rate limits.** \`standard\` = ${stdLimit.perMinute}/min (+${stdLimit.burst} burst), \`elevated\` = ${elevLimit.perMinute}/min (+${elevLimit.burst} burst), \`unlimited\` reserved for internal traffic. \`X-RateLimit-Limit\`, \`X-RateLimit-Remaining\`, \`X-RateLimit-Reset\` returned on every response.`,
    "",
    `**Versioning.** URL prefix \`/v${input.version.split(".")[0]}\`. Additive changes do not bump major; breaking changes do. Deprecated endpoints emit \`Deprecation\` and \`Sunset\` headers (≥ 6 months notice).`,
    "",
    "**CORS.** Explicit allowlist origin (no `*` in production). `Authorization`, `Idempotency-Key`, `X-API-Key`, `X-Request-ID` whitelisted.",
  ].join("\n");
}

function buildQualityGateChecklist(input: GenerateApiSpecInput): string {
  const dupes = findDuplicatePaths(input);
  const missingSunset = input.endpoints.filter((e) => e.deprecated && !e.sunset_date);
  const checks: Array<{ ok: boolean; label: string }> = [
    { ok: dupes.length === 0, label: "All `(method, path)` combinations are unique" },
    {
      ok: input.endpoints.every(
        (e) => !(e.method === "POST" || e.method === "PUT") || e.requires_idempotency,
      ),
      label: "Every POST/PUT requires `Idempotency-Key`",
    },
    {
      ok: input.endpoints.every((e) => e.method !== "GET" || e.pagination_strategy !== undefined),
      label: "Every GET declares a `pagination_strategy`",
    },
    { ok: missingSunset.length === 0, label: "Every deprecated endpoint has a `sunset_date`" },
    {
      ok: input.endpoints.every((e) => e.auth_scheme !== "none") || input.endpoints.length === 0,
      label: "No endpoint defaults to unauthenticated unless explicitly intended",
    },
  ];
  return checks.map((c) => `- [${c.ok ? "x" : " "}] ${c.label}`).join("\n");
}

function buildRecommendations(input: GenerateApiSpecInput, risks: RiskEntry[]): string[] {
  const recs: string[] = [];
  if (risks.some((r) => r.id.startsWith("AUTH-"))) {
    recs.push(
      "Document the rationale for any unauthenticated endpoints in an ADR; require security review sign-off.",
    );
  }
  if (risks.some((r) => r.id.startsWith("IDEMP-"))) {
    recs.push(
      "Enable `requires_idempotency=true` on every state-mutating endpoint to make retries safe by default.",
    );
  }
  if (input.endpoints.some((e) => e.pagination_strategy === "offset")) {
    recs.push(
      "Migrate offset pagination to cursor pagination once datasets exceed 10k rows — offset performance degrades at high values.",
    );
  }
  if (!input.endpoints.some((e) => e.deprecated)) {
    recs.push(
      "Define a deprecation policy now (even with no current deprecations) so future sunsets follow the same playbook.",
    );
  }
  recs.push(
    "Lint the generated YAML with `spectral` and the OWASP API Security ruleset before publishing.",
  );
  recs.push("Generate typed SDKs from this spec to keep clients in lockstep with the contract.");
  return recs;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function quote(s: string): string {
  return `"${s.replace(/"/g, '\\"')}"`;
}

function escape(s: string): string {
  return s.replace(/\|/g, "\\|");
}

function operationId(method: string, p: string): string {
  const cleaned = p
    .replace(/^\//, "")
    .replace(/\{([^}]+)\}/g, "By_$1")
    .replace(/\//g, "_")
    .replace(/-/g, "_");
  return `${method.toLowerCase()}_${cleaned || "root"}`;
}

function deriveTag(p: string): string {
  const first = p.split("/").filter(Boolean)[0] ?? "default";
  return first.replace(/\{[^}]+\}/g, "default") || "default";
}

function uniqueTags(input: GenerateApiSpecInput): string[] {
  return Array.from(new Set(input.endpoints.map((e) => deriveTag(e.path)))).sort();
}

function extractPathParams(p: string): string[] {
  return Array.from(p.matchAll(/\{([^}]+)\}/g)).map((m) => m[1]);
}

function authSchemeRef(scheme: string): string {
  switch (scheme) {
    case "oauth2_client_credentials":
      return "OAuth2ClientCredentials";
    case "api_key":
      return "ApiKey";
    case "bearer_jwt":
    default:
      return "BearerJWT";
  }
}

function responseRef(status: string): string {
  return (
    {
      "400": "BadRequest",
      "401": "Unauthenticated",
      "403": "Unauthorized",
      "404": "NotFound",
      "422": "ValidationFailed",
      "429": "RateLimited",
      "503": "ServiceUnavailable",
    }[status] ?? "BadRequest"
  );
}

function findDuplicatePaths(input: GenerateApiSpecInput): string[] {
  const seen = new Set<string>();
  const dupes: string[] = [];
  for (const e of input.endpoints) {
    const key = `${e.method} ${e.path}`;
    if (seen.has(key)) dupes.push(key);
    seen.add(key);
  }
  return dupes;
}

function countByTier(input: GenerateApiSpecInput): Record<string, number> {
  const counts: Record<string, number> = { standard: 0, elevated: 0, unlimited: 0 };
  for (const e of input.endpoints) {
    counts[e.rate_limit_tier ?? "standard"]++;
  }
  return counts;
}
